### PR TITLE
Add first line to README.md

### PR DESCRIPTION
**Pull request by christophersiem**
I've added a second line to README.md

### CODE REVIEW

**Review by Cobas91 — CHANGES_REQUESTED** [review]
You should write a little bit more text...

**Comment by ankestein** [comment]
Well done.

**Comment by ThiemoOrrico** [comment]
comment test from thiemo

**Review by ankestein — APPROVED** [review]

**Comment by Jan-OkeMettendorf** [comment]
Everything seems to be right

**Pull request merged**
